[package]
name = "solhunt"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "3.2.17", features = [
    "derive",
    "env",
    "unicode",
    "wrap_help",
] }
# ethers-solc = { git = "https://github.com/iFrostizz/ethers-rs.git", rev = "ce3cc16", features = ["svm-solc", "project-util"] }
ethers-solc = { path = "/home/franfran/Projects/utils/ethers-rs/ethers-solc", features = ["svm-solc", "project-util"] }
eyre = "0.6.8"
semver = "1.0.13"
serde = "1.0.143"
# solang-parser = "0.1.17"
serde_json = "1.0.83"
tempfile = "3.3.0"
# ethers-core = "0.17.0"
# ethers-core = { git = "https://github.com/iFrostizz/ethers-rs.git", branch = "f/ast" }
foundry-cli = { path = "/home/franfran/Projects/utils/foundry/cli" }
foundry-config = { path = "/home/franfran/Projects/utils/foundry/config" }
foundry-common = { path = "/home/franfran/Projects/utils/foundry/common" }
yansi = "0.5.1"
