[package]
name = "cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
core = { path = "../core" }
# ethers-solc = { git = "https://github.com/onbjerg/ethers-rs.git", branch = "onbjerg/ast", features = ["project-util"] }
ethers-solc = { version = "0.17.0", features = ["svm-solc", "project-util"] }
semver = "1.0.13"
serde_json = "1.0.83"
