[package]
name = "cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
core = { path = "../core" }
ethers-solc = { version = "0.17.0", features = ["project-util"] }
semver = "1.0.13"
serde_json = "1.0.83"
